'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''


k = 4000000
first, second, sumF = 1, 2, 0
while first < k or second < k:
    if first % 2 == 0: sumF += first
    if second % 2 == 0: sumF += second
    first += second 
    second += first

print(sumF)